name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1065568145771/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-artifact-regist@compact-orb-472513-j5.iam.gserviceaccount.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./QuizWorker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
